"""add user_items

Revision ID: e03cdfc1ffc0
Revises: 11382d72cc29
Create Date: 2026-09-30 23:35:33.908182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e03cdfc1ffc0'
down_revision: Union[str, None] = '11382d72cc29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('want_to_read', 'reading', 'finished', 'dropped')", name='ck_status_values'),
    sa.CheckConstraint('rating IS NULL OR (rating >= 1 AND rating <= 5)', name='ck_rating_range'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'item_id', name='uq_user_item')
    )
    op.create_index(op.f('ix_user_items_id'), 'user_items', ['id'], unique=False)
    op.create_index(op.f('ix_user_items_item_id'), 'user_items', ['item_id'], unique=False)
    op.create_index(op.f('ix_user_items_user_id'), 'user_items', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_items_user_id'), table_name='user_items')
    op.drop_index(op.f('ix_user_items_item_id'), table_name='user_items')
    op.drop_index(op.f('ix_user_items_id'), table_name='user_items')
    op.drop_table('user_items')
    # ### end Alembic commands ###
